from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


VERSION_PATTERN = re.compile(r"[0-9]+(?:\.[0-9]+)*")
REPOSITORY_PATTERN = re.compile(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+")
PATH_COMPONENT_PATTERN = re.compile(r"[A-Za-z0-9_.-]+")
SHA256_PATTERN = re.compile(r"[0-9a-fA-F]{64}")


def validate_version(version: str) -> str:
    normalized = version.strip()
    if VERSION_PATTERN.fullmatch(normalized) is None:
        raise ValueError("Version must contain dot-separated integers, such as 1.2.3.")
    return normalized


def write_build_info(output: Path, version: str, commit: str = "") -> None:
    normalized_version = validate_version(version)
    normalized_commit = commit.strip()
    output.write_text(
        "# Generated by build_release.sh; do not commit.\n"
        f"BUILD_VERSION = {normalized_version!r}\n"
        f"BUILD_COMMIT = {normalized_commit!r}\n",
        encoding="utf-8",
    )


def build_manifest(
    *,
    version: str,
    repository: str,
    release_tag: str,
    asset_name: str,
    sha256: str,
    release_notes: list[str] | None = None,
) -> dict:
    normalized_version = validate_version(version)
    normalized_repository = repository.strip()
    if REPOSITORY_PATTERN.fullmatch(normalized_repository) is None:
        raise ValueError("Repository must be in owner/name format.")

    normalized_tag = release_tag.strip()
    normalized_asset = asset_name.strip()
    if (
        PATH_COMPONENT_PATTERN.fullmatch(normalized_tag) is None
        or PATH_COMPONENT_PATTERN.fullmatch(normalized_asset) is None
    ):
        raise ValueError("Release tag and asset name contain unsupported characters.")

    normalized_sha256 = sha256.strip().lower()
    if SHA256_PATTERN.fullmatch(normalized_sha256) is None:
        raise ValueError("SHA-256 must contain exactly 64 hexadecimal characters.")

    notes = [note.strip() for note in (release_notes or []) if note.strip()]
    if not notes:
        notes = ["Automatic update built from the latest code on the main branch."]

    return {
        "latest_version": normalized_version,
        "macos_zip_url": (
            f"https://github.com/{normalized_repository}/releases/download/"
            f"{normalized_tag}/{normalized_asset}"
        ),
        "sha256": normalized_sha256,
        "release_notes": notes,
    }


def write_manifest(output: Path, **kwargs) -> None:
    manifest = build_manifest(**kwargs)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate Syllora release metadata.")
    commands = parser.add_subparsers(dest="command", required=True)

    build_info = commands.add_parser("build-info", help="Write generated build version metadata.")
    build_info.add_argument("--output", type=Path, required=True)
    build_info.add_argument("--version", required=True)
    build_info.add_argument("--commit", default="")

    manifest = commands.add_parser("manifest", help="Write the updater's latest.json manifest.")
    manifest.add_argument("--output", type=Path, required=True)
    manifest.add_argument("--version", required=True)
    manifest.add_argument("--repository", required=True)
    manifest.add_argument("--release-tag", required=True)
    manifest.add_argument("--asset-name", required=True)
    manifest.add_argument("--sha256", required=True)
    manifest.add_argument("--note", action="append", default=[])
    return parser


def main() -> None:
    args = _parser().parse_args()
    if args.command == "build-info":
        write_build_info(args.output, args.version, args.commit)
        return

    write_manifest(
        args.output,
        version=args.version,
        repository=args.repository,
        release_tag=args.release_tag,
        asset_name=args.asset_name,
        sha256=args.sha256,
        release_notes=args.note,
    )


if __name__ == "__main__":
    main()
