APP_NAME = "Syllora"
APP_DISPLAY_NAME = "Syllora"
APP_BUNDLE_NAME = f"{APP_DISPLAY_NAME}.app"
APP_BUNDLE_IDENTIFIER = "com.arnoreli.syllora"
APP_RELEASE_ARCHIVE_PREFIX = "Syllora"
APP_SETTINGS_ORG = APP_NAME
APP_SETTINGS_APP = APP_NAME
APP_DB_FILENAME = "syllora.sqlite"
APP_VERSION = "1.0.9"

LEGACY_APP_NAME = "GradeTracker"
LEGACY_APP_DISPLAY_NAME = "Grade Tracker"
LEGACY_APP_BUNDLE_NAME = f"{LEGACY_APP_DISPLAY_NAME}.app"
LEGACY_APP_SETTINGS_ORG = LEGACY_APP_NAME
LEGACY_APP_SETTINGS_APP = LEGACY_APP_NAME
LEGACY_DB_FILENAME = "gradetracker.sqlite"

GITHUB_REPO_SLUG = "arnoreli53/Syllora"
UPDATE_TEST_CURRENT_VERSION_ENV = "SYLLORA_UPDATE_TEST_CURRENT_VERSION"
LEGACY_UPDATE_TEST_CURRENT_VERSION_ENV = "GRADETRACKER_UPDATE_TEST_CURRENT_VERSION"
